name:                scraper
version:             0.1.0.0

dependencies:
- base

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - extra
    - text
    - dlist

executables:
  stack-error-scraper:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - scraper
    - text
    - with-utf8

tests:
  scraper-test:
    main:                Spec.hs
    build-tools: hspec-discover
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - scraper
    - hspec
    - text
    - raw-strings-qq
