#!/bin/bash
#make bash fall over better
set -o pipefail

#we are expecting console output to a file called errorLog
# run stack like this stack build ... --colour always 2>&1 | tee errorLog
# it knows tee is there so switches colour off otherwise
tempFile=.errors-temp
rm -f $tempFile

# remove colour from the logs
ansifilter -i errorLog -o .errors-temp
stack exec scraper -- .errors-temp .errors

rm $tempFile 
